### ISSUE TITLE
Test Results (2024-2-22)

### ISSUE THREAD

**Issue by xuruiyang2002** [xuruiyang2002/closed-box-functions#1]
klee: experiment-refactor (ded2cb)
krpk: refactor-mir (8cfa2b)

# cstring

## Passed

memcmp: 3/3 
strcmp: 3/3
memcpy: 2/2
memmove: 2/2
memset: 2/2
strcspn: 2/2
strcoll: 3/3
strlen: 2/2
strncmp: 3/3
strspn: 2/2
strxfrm: 3/3
strstr: 1/2
### Sometimes fuzz failed 
strpbrk: 2/2, sometimes 1/1
strrchr: 2/2, somtimes 1/1/
strchr: 2/2, sometimes 1/1

## Fuzz failed
memchr (1/2)
KRPK Unknown, the constraint below is unable to solve:

```
(query [(Eq 0 (Read w8 1 array))
         (Eq N0:(ReadLSB w64 0 colossus_fresh_var_arr1)
             (ExtOp w64 "memchr" 47940096 101 1))]
        (Eq 47940096 N0))
```

which is corresponding with the code snippet in C level:

```
char *p = (char*)memchr(str, 'e', 1);
if (p == str) { /// <=== krpk is unable to solve this condition
	printf("Yes\n");
}
...
```
## strerror: out of bound pointer

Stuck in infinite loop of filtering constraints, which finally leads to out of bound.
It's probably a problem that occurred when refactoring the KLEE, I'll debug it later.

## strcat: failed to compile fuzz program

```
thread '<unnamed>' panicked at src/fuzzend/libfuzzer.rs:45:13:
Failed to compile fuzz program: /tmp/ec3780ac-5099-476d-9357-ec464eb94bfc.ywYudq9ilrdP/fuzz.cpp:653:85: error: no matching function for call to 'strcat'
SMTBitVec<64> expr_38 = SMTBitVec<64>(mem_proxy_0_29573858.original_addr((uint64_t) strcat(((const char*) mem_proxy_0_29573858.proxy_addr(expr_36.raw_value())), ((const char*) mem_proxy_0_29573858.proxy_addr(expr_37.raw_value())))));
                                                                                    ^~~~~~
/usr/include/string.h:149:14: note: candidate function not viable: 1st argument ('const char *') would lose const qualifier
extern char *strcat (char *__restrict __dest, const char *__restrict __src)

```

## strcpy: failed to compile fuzz program

```
thread '<unnamed>' panicked at src/fuzzend/libfuzzer.rs:45:13:
Failed to compile fuzz program: /tmp/f58b6cd3-8122-424c-a30b-7d06ef660876.VOoyPsyiIJ7A/fuzz.cpp:673:85: error: no matching function for call to 'strcpy'
SMTBitVec<64> expr_38 = SMTBitVec<64>(mem_proxy_0_34341234.original_addr((uint64_t) strcpy(((const char*) mem_proxy_0_34341234.proxy_addr(expr_36.raw_value())), ((const char*) mem_proxy_0_34341234.proxy_addr(expr_37.raw_value())))));
                                                                                    ^~~~~~
/usr/include/string.h:141:14: note: candidate function not viable: 1st argument ('const char *') would lose const qualifier
extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
```

## strncat: failed to compile fuzz program

```
thread '<unnamed>' panicked at src/fuzzend/libfuzzer.rs:45:13:
Failed to compile fuzz program: /tmp/404fa09f-27c4-458e-a137-c394f332b69a.LgVU8WJDNB2g/fuzz.cpp:659:85: error: no matching function for call to 'strncat'
SMTBitVec<64> expr_39 = SMTBitVec<64>(mem_proxy_0_26886882.original_addr((uint64_t) strncat(((const char*) mem_proxy_0_26886882.proxy_addr(expr_36.raw_value())), ((const char*) mem_proxy_0_26886882.proxy_addr(expr_37.raw_value())), static_cast<unsigned long long>(expr_38.raw_value()))));
                                                                                    ^~~~~~~
/usr/include/string.h:152:14: note: candidate function not viable: 1st argument ('const char *') would lose const qualifier
extern char *strncat (char *__restrict __dest, const char *__restrict __src,
```
## strncpy: failed to compile fuzz program

```
thread '<unnamed>' panicked at src/fuzzend/libfuzzer.rs:45:13:
Failed to compile fuzz program: /tmp/e5fc117c-a52b-4db9-825e-808c2419f6b5.uqRIcKeUHDCG/fuzz.cpp:657:85: error: no matching function for call to 'strncpy'
SMTBitVec<64> expr_39 = SMTBitVec<64>(mem_proxy_0_29761906.original_addr((uint64_t) strncpy(((const char*) mem_proxy_0_29761906.proxy_addr(expr_36.raw_value())), ((const char*) mem_proxy_0_29761906.proxy_addr(expr_37.raw_value())), static_cast<unsigned long long>(expr_38.raw_value()))));
                                                                                    ^~~~~~~
/usr/include/string.h:144:14: note: candidate function not viable: 1st argument ('const char *') would lose const qualifier
extern char *strncpy (char *__restrict __dest,
```

```
strtok: thread '<unnamed>' panicked at src/smtanalyze/analyzer.rs:822:49:
not implemented: Only support array select with constant index.
```

## System call

```
getpid: 2/2
open: 2/2
read_write: 2/2
```

## Excerpted from logic bomb

Tests that do not involve floating point numbers (such as `atoi`, `rand`, etc.) are no problem, but tests involving floating point numbers are not supported, such as `pow`, `atof`, etc.

**Comment by tingsu** [comment]
Thanks for the testing report, @xuruiyang2002 . You guys need to investigate the issues.
