### ISSUE TITLE
Test Results

### ISSUE THREAD

**Issue by xuruiyang2002** [xuruiyang2002/closed-box-functions#2]
The test results in #1 is inaccurate due to lack of whitelist. I have expanded the whitelist (CB_FUNCTION_LIST) and did a new round of testing.

**Comment by xuruiyang2002** [comment]
(2024-2-23)
klee: experiment-refactor (ded2cb)
krpk: refactor-mir (8cfa2b)

# cstring

### Passed

memcmp: 3/3 
strcmp: 3/3
memcpy: 2/2
memmove: 2/2
memset: 2/2
strcspn: 2/2
strcoll: 3/3
strlen: 2/2
strncmp: 3/3
strspn: 2/2

### Sometimes fuzz failed 
strpbrk: 2/2, sometimes 1/1
strrchr: 2/2, somtimes 1/1/
strchr: 2/2, sometimes 1/1
strstr: sometimes 1/1
memchr (1/2)

### strerror: out of bound pointer

Stuck in infinite loop of filtering constraints, which finally leads to out of bound.
It's probably a problem that occurred when refactoring the KLEE, I'll debug it later.

**UPDATE**: 
The problem "out of bound pointer" is due to my inappropriate design of test case.
I haven't figured out how to write test case for `strerror`, which is a special function.
I'll put it off.

### strcat: failed to compile fuzz program

```
KLEE: WARNING: DEBUG: Using KRPK to compute test cases
KLEE: DEBUG: Query to KRPK is: array array[2] : w32 -> w8 = symbolic
array colossus_fresh_var_arr1[8] : w32 -> w8 = symbolic
(query [(Eq 0 (Read w8 1 array))
         (Eq (ReadLSB w64 0 colossus_fresh_var_arr1)
             (ExtOp w64 "strcat" 33170136 33170144))]
        true)

thread '<unnamed>' panicked at src/fuzzend/libfuzzer.rs:45:13:
Failed to compile fuzz program: /tmp/730f3c32-2799-400b-ab4c-bdb5b5eaddbc.ngqz3IoO6DKu/fuzz.cpp:648:85: error: no matching function for call to 'strcat'
SMTBitVec<64> expr_38 = SMTBitVec<64>(mem_proxy_0_33170146.original_addr((uint64_t) strcat(((const char*) mem_proxy_0_33170146.proxy_addr(expr_36.raw_value())), ((const char*) mem_proxy_0_33170146.proxy_addr(expr_37.raw_value())))));
                                                                                    ^~~~~~
/usr/include/string.h:149:14: note: candidate function not viable: 1st argument ('const char *') would lose const qualifier
extern char *strcat (char *__restrict __dest, const char *__restrict __src)
             ^
1 error generated.
```
The same errors occur in the `strcat`, `strcpy`, `strncpy`, and `strxfrm`.

### strtok: only support array select with constant index.

```
KLEE: WARNING: DEBUG: Invoking KRPK getFeasibleAssignmemt
KLEE: DEBUG: Query to KRPK is: array colossus_fresh_var_arr1[8] : w32 -> w8 = symbolic
array const_arr1[3] : w32 -> w8 = [97 45 0]
(query [(Eq N0:(ReadLSB w64 0 colossus_fresh_var_arr1)
             (ExtOp w64 "strtok" 23257792 23257784))]
        (Eq 0
            (Read w8 (Extract w32 0 (Add w64 18446744073686293825 N0))
                     const_arr1)))

thread '<unnamed>' panicked at src/smtanalyze/analyzer.rs:822:49:
not implemented: Only support array select with constant index.
```
This is because the KRPK now doesn't support non-constant index arrays.

## System call

FIXME: The`getpid` is an external function that requires no input but produces a return value.
~~In my refactoring implementation, the part was not taken into account~~

**UPDATE**: Since the `getpid` requires no input, the fuzzer is unable to fuzz it.

FIXME: KLEE thinks of `open`, `read` etc as an external function with variable arguments. Maybe KLEE has a special treatment with these.

**UPDATE**: REColossus doesn't support handling system calls.

## Excerpted from logic bomb

### rand_ef_l2 (2/2)

### atoi_ef_l2

KLEE thinks of `atoi` as an external function with vararg 
**UPDATE**: Test case misses the head file `stdlib.h`, not the fault of KLEE. I have fixed.

Now the test result is 1/2, `unable to compute initial value`.

### pow_ef_l2

```
klee: /home/user/recolossus/klee/include/klee/Expr/Expr.h:1235:
virtual klee::Expr::Width klee::ExtOpExpr::getWidth() const: Assertion `0 && "width in isPointerTy of extop to be handled\n"' failed.
```

### sin_el_l2

```
klee: /home/user/recolossus/klee/include/klee/Expr/Expr.h:1235:
virtual klee::Expr::Width klee::ExtOpExpr::getWidth() const: Assertion `0 && "width in isPointerTy of extop to be handled\n"' failed.
```

### atof_ef_l2

```
klee: /home/user/recolossus/klee/lib/Core/Executor.cpp:2379: std::vector<ref<Expr>> 
klee::Executor::specialHandleForPointerInArgs(llvm::Function *, klee::ExecutionState &, std::vector<Cell *>, std::vector<ref<Expr>>): Assertion `!func->isVarArg() && "vararg is not supported yet"' failed.
```
**UPDATE**
The problem is same as `atoi` faced. After refining the test case, a new problem arose:
```
klee: /home/user/recolossus/klee/include/klee/Expr/Expr.h:1235: 
virtual klee::Expr::Width klee::ExtOpExpr::getWidth() const: Assertion `0 && "width in isPointerTy of extop to be handled\n"' failed.
```
This is because klee-recolossus doesn't support the float.

### ln_ef_l2

```
klee: /home/user/recolossus/klee/include/klee/Expr/Expr.h:1235:
virtual klee::Expr::Width klee::ExtOpExpr::getWidth() const: Assertion `0 && "width in isPointerTy of extop to be handled\n"' failed.
```
I'll debug these later.

**Comment by xuruiyang2002** [comment]
Careful consideration of the test results reveals the capabilities of our `klee-recolossus`:
1. Our implementation is able to handle more than half of the `cstring` test cases, except for some `compile errors` which may due to the closure problem in `krpk`.
2. Now doesn't support:
2.1 Non-constant index array theory
2.2 System call
2.3 Floating point

**Comment by xuruiyang2002** [comment]
> 2024-2-26
> KLEE: experiment-refactor (b03c404)
> KRPK: refactor-mir (c0a59b)
> options: /home/user/recolossus/build/bin/klee --recolossus --warnings-only-to-file --max-time=600 --max-fuzz-solver-time=30 --search=dfs -rewrite-equalities=false --external-calls=all 

Test each test case at least 3 times
## cstring

### Pass
``` c
strcmp strcspn strcoll strlen strxfrm
strchr strspn strncmp strpbrk strrchr strstr memchr
```
### Not create ExtOp
```
// --> Becasue the returnArgValues is empty
// ----> Because they are considered as declaration
memcmp memcpy memmove memset
```

### Couldn't find all paths

```
strcat strncat strcpy strncpy
```
### Others

Haven't figured out how to write test case for `strerror`, which is a special function.

```
strerror
```

Only support array select with constant index. This is because the KRPK now doesn't support non-constant index arrays.

```
 strtok
```

## System call

Not currently supported
## Excerpted from logic bomb

### Passed

```
rand_ef_l2
atoi_ef_l2
```

### Failed because not support floating point

```
pow_ef_l2
sin_el_l2
atof_ef_l2
ln_ef_l2
```

The error message is as follows: 

```
klee: /home/user/recolossus/klee/include/klee/Expr/Expr.h:1235:
virtual klee::Expr::Width klee::ExtOpExpr::getWidth() const:
Assertion `0 && "width in isPointerTy of extop to be handled\n"' failed.
```
